site_name: "Tactical RMM Documentation"
nav:
  - Home: index.md
  - Sponsor: sponsor.md
  - Code Signing: code_signing.md
  - Support: support.md
  - Roadmap: roadmap.md
  - Getting Started Guide: guide_gettingstarted.md
  - RMM Server Installation:
      - "Install Considerations": install_considerations.md
      - "Traditional Install": install_server.md
      - "Docker Install": install_docker.md
  - RMM Server Updating:
      - "Updating the RMM": update_server.md
      - "Updating the RMM (Docker)": update_docker.md
  - Agents:
      - "Agent Installation": install_agent.md
      - "Updating Agents": update_agents.md
  - Functionality:
      - "How it all Works": howitallworks.md
      - "Alerting": functions/alerting.md
      - "API Access": functions/api.md
      - "Automated Tasks": functions/automated_tasks.md
      - "Automation Policies": functions/automation_policies.md
      - "Custom Fields": functions/custom_fields.md
      - "Database Maintenance": functions/database_maintenance.md
      - "Django Admin": functions/django_admin.md
      - "Email & SMS Alerts": functions/emailsms_alert.md
      - "Global Keystore": functions/keystore.md
      - "Maintenance Mode": functions/maintenance_mode.md
      - "Permissions": functions/permissions.md
      - "Remote Background": functions/remote_bg.md
      - "Overriding / Customizing Default Settings": functions/settings_override.md
      - "Scripting": functions/scripting.md
      - "URL Actions": functions/url_actions.md
      - "User Interface Preferences": functions/user_ui.md
      - "Reference: Script Variables": script_variables.md
      - "Examples": functions/examples.md
  - Reporting:
      - "Overview": ee/reporting/reporting_overview.md
      - "- FAQ": ee/reporting/functions/faq.md
      - "- The Basics": ee/reporting/functions/reporting_basics.md
      - "- Base Templates": ee/reporting/functions/reporting_basetemplates.md
      - "- Variables": ee/reporting/functions/reporting_variables.md
      - "- Data Queries": ee/reporting/functions/reporting_dataqueries.md
      - "- Assets": ee/reporting/functions/reporting_assets.md
      - "- Tips n' Tricks": ee/reporting/functions/tipsntricks.md
      
  - Backup: backup.md
  - Restore: restore.md
  - Antivirus Exclusions: av.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md
  - Management Commands: management_cmds.md
  - MeshCentral Integration: mesh_integration.md
  - 3rd Party Integrations:
      - "Grafana": 3rdparty_grafana.md
      - "AnyDesk": 3rdparty_anydesk.md
      - "N-Able": 3rdparty_n-able-takecontrol.md
      - "Bomgar": 3rdparty_bomgar.md
      - "ConnectWise Control / ScreenConnect": 3rdparty_screenconnect.md
      - "RustDesk": 3rdparty_rustdesk.md
      - "Splashtop": 3rdparty_splashtop.md
      - "Supremo": 3rdparty_supremo.md
      - "TeamViewer": 3rdparty_teamviewer.md
      - "BitDefender GravityZone": 3rdparty_bitdefender_gravityzone.md
      - "BitDefender Total Security": 3rdparty_bitdefender_total_security.md
  - Unsupported Extras:
      - "Unsupported Guidelines": unsupported_guidelines.md
      - "Unsupported Configs": unsupported_scripts.md
      - "Securing nginx": securing_nginx.md
      - "Unsupported Proxies": unsupported_proxies.md
      - "Installing in Synology Docker": unsupported_synology_docker_install.md
      - "Installing on other platforms": unsupported_platforms.md
  - Tips n' Tricks: tipsntricks.md
  - Contributing:
      - "Contributing to Docs": contributing.md
      - "Contributing to Community Scripts": contributing_community_scripts.md
      - "Contributing to Reporting Templates": contributing_reporting_templates.md      
      - "Contributing using a browser": contributing_using_browser.md
      - "Contributing using VS Code": contributing_using_vscode.md
      - "Contributing using Docker": contributing_using_docker.md
      - "Contributing using a Remote Server": contributing_using_a_remote_server.md
  - Security: security.md
  - License: license.md
site_description: "A remote monitoring and management tool"
site_author: "amidaware"
site_url: "https://docs.tacticalrmm.com/"

dev_addr: "0.0.0.0:8005"

# Repository
repo_name: "amidaware/tacticalrmm"
repo_url: "https://github.com/amidaware/tacticalrmm"
edit_uri: ""

theme:
  name: "material"
  logo: "images/onit.ico"
  favicon: "images/favicon.ico"
  features:
    - content.code.copy
  language: "en"
  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: light)"
    scheme: light
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/amidaware/tacticalrmm"

markdown_extensions:
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.keys
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - neoteroi.projects
